# docker-compose.yml
version: '3.8'

services:
  recommender-implicit:
    build:
      context: .
      dockerfile: dockerfile
    container_name: book-rec-implicit
    restart: unless-stopped
    env-file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_MODULE=server:app
      - HOST=0.0.0.0
      - PORT=8003
      - WORKE8002
      - AUTO_TRAIN=false

      # Database (giữ nguyên)
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}

      # Kết nối RabbitMQ qua SSH tunnel
      # Container → host VPS2 → tunnel → RabbitMQ VPS1
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@host.docker.internal:5672

      # Callback về backend VPS1 qua IP thật
      - JAVA_BACKEND_URL=http://${BACKEND_HOST}:8080/api/v1
      - CALLBACK_ENABLED=true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    networks:
      - rs-network
    ports:
      - "8003:8003"